whoami-app:
  component: sls-component-http
  inputs:
    region: ap-guangzhou
    functionName: whoami
    runtime: Nodejs10.15
    functionConf:
      timeout: 60
      memorySize: 128
      environment:
        variables:
          TOKEN: token
    apigatewayConf:
      protocols:
        - https
      environment: release

